apiVersion: v1
kind: ServiceAccount
metadata:
  name: installer-dev
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installer-dev
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: installer-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: installer-dev
subjects:
- kind: ServiceAccount
  name: installer-dev
  namespace: default