kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# name: krateo-quickstart
nodes:
  - extraPortMappings:
    - containerPort: 30090 # VCluster
      hostPort: 30090
    - containerPort: 30080 # Krateo Portal
      hostPort: 30080
    - containerPort: 30081 # Krateo BFF
      hostPort: 30081
    - containerPort: 30082 # Krateo AuthN Service
      hostPort: 30082
    - containerPort: 30443 # Krateo Gateway
      hostPort: 30443
networking:
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
